version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://product_user:product_password@db:3306/product_management
      - DEBUG=true
      - LOG_LEVEL=INFO
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - product-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=product_management
      - MYSQL_USER=product_user
      - MYSQL_PASSWORD=product_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - product-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - product-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  product-network:
    driver: bridge 